web:
  restart: always
  build: ./
  expose:
    - "8000"
  links:
    - postgres:postgres
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - web:web

postgres-data:
  restart: "no"
  image: postgres:9.3
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:9.3
  volumes_from:
    - postgres-data
  ports:
    - "5432:5432"

mongo-data:
  restart: "no"
  image: mongo:3.2.1
  volumes:
    - /data/db
  command: "true"

mongo:
  restart: always
  image: mongo:3.2.1
  volumes_from:
    - mongo-data
  ports:
    - "27017:27017"
